### PR TITLE
Extend the wfd::Peer::Delegate interface to get the real 'wfd-presentatio...

### PR DESCRIPTION
**Pull request by pozdnyakov**
...n-url'

This patch also adds generic constants for the RTSP reply codes.

### CODE REVIEW

**Comment by kanavin** [comment]
Jussi K. should say where the IP address getter belongs - in media manager or maybe in Delegate (since that's where the p2p network handling happens).

**Comment by pozdnyakov** [comment]
@kanavin I think it's might be better indeed to move it to Peer::Delegate

**Comment by pozdnyakov** [comment]
moved IP getter to Peer::Delegate since it fits better for the network communication

**Comment by jku** [comment]
LGTM

**Pull request merged**
